//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File1
        ///.
        /// </summary>
        public static string File1 {
            get {
                return ResourceManager.GetString("File1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File2
        ///.
        /// </summary>
        public static string File2 {
            get {
                return ResourceManager.GetString("File2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File3.
        /// </summary>
        public static string File3 {
            get {
                return ResourceManager.GetString("File3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File4.
        /// </summary>
        public static string File4 {
            get {
                return ResourceManager.GetString("File4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File5.
        /// </summary>
        public static string File5 {
            get {
                return ResourceManager.GetString("File5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File6
        ///File6
        ///File6
        ///File6
        ///File6.
        /// </summary>
        public static string File6 {
            get {
                return ResourceManager.GetString("File6", resourceCulture);
            }
        }
    }
}
